version: '3.7'

services:
  web:
    build:
      context:
      dockerfile: Dockerfile
    image: Project3a_app_image_flask
    container_name: Stock_app_Project3a
    ports:
    - "5005:5000"
    volumes:
    - .:/app
    environment:
      FLASK_DEBUG: "1"
